
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dalkmtcemlflggpkqprn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhbGttdGNlbWxmbGdncGtxcHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNjIyNDMsImV4cCI6MjA0OTczODI0M30.z31EP4bKhXsT1L2VHUxIben9lC6w_VZl-SnRj0ybkkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false // Changed from true to false to avoid URL fragment issues
    },
    global: {
      headers: {
        'X-Client-Info': 'guidecampus-webapp'
      }
    }
  }
);
